# Copyright 2014 SURFnet bv
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

services:
    # Write Services
    surfnet_stepup_middleware_client.service.command:
        class: Surfnet\StepupMiddlewareClientBundle\Service\CommandService
        arguments:
            - @surfnet_stepup_middleware_client.library.service.command
            - @logger

    # Read Services
    surfnet_stepup_middleware_client.identity.service.identity:
        class: Surfnet\StepupMiddlewareClientBundle\Identity\Service\IdentityService
        arguments:
            - @surfnet_stepup_middleware_client.library.identity.service.identity
            - @validator

    surfnet_stepup_middleware_client.identity.service.institution_listing:
        class: Surfnet\StepupMiddlewareClientBundle\Identity\Service\InstitutionListingService
        arguments:
            - @surfnet_stepup_middleware_client.library.identity.service.institution_listing
            - @validator

    surfnet_stepup_middleware_client.identity.service.second_factor:
        class: Surfnet\StepupMiddlewareClientBundle\Identity\Service\SecondFactorService
        arguments:
            - @surfnet_stepup_middleware_client.library.identity.service.second_factor
            - @validator

    surfnet_stepup_middleware_client.identity.service.ra_second_factor:
        class: Surfnet\StepupMiddlewareClientBundle\Identity\Service\RaSecondFactorService
        arguments:
            - @surfnet_stepup_middleware_client.library.identity.service.ra_second_factor
            - @validator

    surfnet_stepup_middleware_client.identity.service.ra:
        class: Surfnet\StepupMiddlewareClientBundle\Identity\Service\RaService
        arguments:
            - @surfnet_stepup_middleware_client.library.identity.service.ra
            - @validator

    surfnet_stepup_middleware_client.identity.service.ra_listing:
        class: Surfnet\StepupMiddlewareClientBundle\Identity\Service\RaListingService
        arguments:
            - @surfnet_stepup_middleware_client.library.identity.service.ra_listing
            - @validator

    # Library Services
    surfnet_stepup_middleware_client.library.service.command:
        public: false
        class: Surfnet\StepupMiddlewareClient\Service\CommandService
        arguments:
            - @surfnet_stepup_middleware_client.guzzle.commands
            - ~ # Username, overridden in extension
            - ~ # Password, overridden in extension

    surfnet_stepup_middleware_client.library.identity.service.identity:
        public: false
        class: Surfnet\StepupMiddlewareClient\Identity\Service\IdentityService
        arguments:
            - @surfnet_stepup_middleware_client.library.service.api

    surfnet_stepup_middleware_client.library.identity.service.institution_listing:
        public: false
        class: Surfnet\StepupMiddlewareClient\Identity\Service\InstitutionListingService
        arguments:
            - @surfnet_stepup_middleware_client.library.service.api

    surfnet_stepup_middleware_client.library.identity.service.ra:
        public: false
        class: Surfnet\StepupMiddlewareClient\Identity\Service\RaService
        arguments:
            - @surfnet_stepup_middleware_client.library.service.api

    surfnet_stepup_middleware_client.library.identity.service.ra_listing:
        public: false
        class: Surfnet\StepupMiddlewareClient\Identity\Service\RaListingService
        arguments:
            - @surfnet_stepup_middleware_client.library.service.api

    surfnet_stepup_middleware_client.library.identity.service.ra_second_factor:
        public: false
        class: Surfnet\StepupMiddlewareClient\Identity\Service\RaSecondFactorService
        arguments:
            - @surfnet_stepup_middleware_client.library.service.api

    surfnet_stepup_middleware_client.library.identity.service.second_factor:
        public: false
        class: Surfnet\StepupMiddlewareClient\Identity\Service\SecondFactorService
        arguments:
            - @surfnet_stepup_middleware_client.library.service.api

    # Client Services
    surfnet_stepup_middleware_client.guzzle.commands:
        public: false
        class: GuzzleHttp\Client
        arguments:
            - ~ # Guzzle options, overridden in extension

    surfnet_stepup_middleware_client.library.service.api:
        public: false
        class: Surfnet\StepupMiddlewareClient\Service\ApiService
        arguments:
            - @surfnet_stepup_middleware_client.guzzle.api

    surfnet_stepup_middleware_client.guzzle.api:
        public: false
        class: GuzzleHttp\Client
        arguments:
            - ~ # Guzzle options, overridden in extension
